// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: CAN_Display

#include "ui.h"

lv_obj_t * uic_Test;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_VOLT = NULL;
lv_obj_t * ui_POWER = NULL;
lv_obj_t * ui_TEMP = NULL;
lv_obj_t * ui_SOC = NULL;
lv_obj_t * ui_TEXT1 = NULL;
lv_obj_t * ui_TEXT2 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_COMMS = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VOLT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VOLT, 300);
    lv_obj_set_height(ui_VOLT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOLT, 0);
    lv_obj_set_y(ui_VOLT, -103);
    lv_obj_set_align(ui_VOLT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOLT, "VOLT");

    ui_POWER = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_POWER, 300);
    lv_obj_set_height(ui_POWER, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POWER, 0);
    lv_obj_set_y(ui_POWER, -83);
    lv_obj_set_align(ui_POWER, LV_ALIGN_CENTER);
    lv_label_set_text(ui_POWER, "POWER");
    lv_obj_set_style_text_align(ui_POWER, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEMP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TEMP, 300);
    lv_obj_set_height(ui_TEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMP, 0);
    lv_obj_set_y(ui_TEMP, -63);
    lv_obj_set_align(ui_TEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMP, "TEMP");
    lv_obj_clear_flag(ui_TEMP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_TEMP, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOC = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SOC, 300);
    lv_obj_set_height(ui_SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SOC, 0);
    lv_obj_set_y(ui_SOC, -3);
    lv_obj_set_align(ui_SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOC, "SOC");

    ui_TEXT1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TEXT1, 300);
    lv_obj_set_height(ui_TEXT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEXT1, 0);
    lv_obj_set_y(ui_TEXT1, -43);
    lv_obj_set_align(ui_TEXT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEXT1, "TEXT1");

    ui_TEXT2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TEXT2, 300);
    lv_obj_set_height(ui_TEXT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEXT2, 0);
    lv_obj_set_y(ui_TEXT2, -23);
    lv_obj_set_align(ui_TEXT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEXT2, "TEXT2");

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 22);
    lv_obj_set_height(ui_Bar1, 39);
    lv_obj_set_x(ui_Bar1, -140);
    lv_obj_set_y(ui_Bar1, 92);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 32);
    lv_obj_set_height(ui_Spinner1, 32);
    lv_obj_set_x(ui_Spinner1, 137);
    lv_obj_set_y(ui_Spinner1, 96);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_COMMS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_COMMS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_COMMS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_COMMS, 74);
    lv_obj_set_y(ui_COMMS, 97);
    lv_obj_set_align(ui_COMMS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_COMMS, "COMMS");

    uic_Test = ui_Screen1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Test = NULL;
    ui_Screen1 = NULL;
    ui_VOLT = NULL;
    ui_POWER = NULL;
    ui_TEMP = NULL;
    ui_SOC = NULL;
    ui_TEXT1 = NULL;
    ui_TEXT2 = NULL;
    ui_Bar1 = NULL;
    ui_Spinner1 = NULL;
    ui_COMMS = NULL;

}
