// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: CAN_Display

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_VOLT;
extern lv_obj_t * ui_POWER;
extern lv_obj_t * ui_TEMP;
extern lv_obj_t * ui_SOC;
extern lv_obj_t * ui_TEXT1;
extern lv_obj_t * ui_TEXT2;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_COMMS;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Test;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

